[package]
name = "chunker"
version = "0.1.0"
authors = ["Wesley Aptekar-Cassels <me@wesleyac.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
regex = "1.10.4"
serialport = "3.2.0"
structopt = "0.3.14"
